### ISSUE TITLE
RCRM Job candidate Rejected Status Integration loop

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-app#142] opened 2021-04-08 04:48 UTC
Inifinite loop scenario happening with the Zap: 5 PROD - JOBCANDIDATE Update All Status RCRM to TaaS and  4-PROD-JOBCANDIDATE-Status-to-Rcrm

**Comment by maxceem** [comment] 2021-04-08 09:16
### References:

- We had a similar issue with `shortlisted` status https://github.com/topcoder-platform/taas-app/issues/114
- We fixed by 3 PRs:
   - https://github.com/topcoder-platform/taas-apis/pull/159/files
   - https://github.com/topcoder-platform/taas-es-processor/pull/27/files
   - https://github.com/topcoder-platform/taas-app/pull/115/files
 
### Suggested fix:

As have been discussed on Slack we would add a new status `topcoder-rejected` to indicate that candidate has been rejected in RCRM.

**Comment by maxceem** [comment] 2021-04-09 08:01
We found out the root cause of this issue and fixed it via https://github.com/topcoder-platform/taas-es-processor/pull/33.

The general idea of the fix, we should not post to Zapier to update status, if status was not really updated. Added the next unit tests which verify this logic:
- should post to Zapier if status is changed to “rejected”
- should post to Zapier if status is changed to “shortlist”
- should **not** post to Zapier if status was already “rejected” and updated to “rejected”
- should **not** post to Zapier if status was already “shortlist” and updated to “shortlist”
- should **not** post to Zapier if status is changed to “interview” or another one (not “rejected” or “shortlist”)
- should **not** post to Zapier if status is changed to "topcoder-rejected" (not "rejected" or "shortlist")

Though it appears that there was a second part of issue:
- when rejecting JC from RCRM we want the JC status to be Topcoder Rejected (`topcoder-rejected`)
- while when rejecting JS from TaaS we want the JS status to be Client Rejected (`rejected`)

For this purpose, we added support for a new status `topcoder-rejected` to Job Candidates.

DEV PRs
- ES Processor https://github.com/topcoder-platform/taas-es-processor/pull/35
- TaaS API https://github.com/topcoder-platform/taas-apis/pull/187
- TaaS App https://github.com/topcoder-platform/taas-app/pull/144

PROD PRs
- ES Processor https://github.com/topcoder-platform/taas-es-processor/pull/34
- TaaS API https://github.com/topcoder-platform/taas-apis/pull/186
- TaaS App https://github.com/topcoder-platform/taas-app/pull/143

**Comment by SathyaJayabal** [comment] 2021-04-09 09:58
Verified the status updates between RCRM and TaaS App after the addition of the new status. The syncing of the statuses between the apps is working fine on Dev.

**Comment by SathyaJayabal** [comment] 2021-04-09 13:12
Verified the status updates between RCRM and TaaS App after the addition of the new status. The syncing of the statuses between the apps is working fine on Prod.

**Closed by SathyaJayabal** 2021-04-09 13:12 UTC
Labels: P0, QA Pass on Dev
