### ISSUE TITLE
Project Access Management Controls

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-app#14] opened 2020-12-03 15:39 UTC
Need to implement a solution for managing access to a project (team) within taas-app.

Option 1 (low effort) - add a link to Connect to perform team management functions inside Connect.

Option 2 (higher effort) - Update TaaS App Team Details page with controls to add users to the team, similar to Connect project control. TaaS app would only implement "topcoder" and "team" - topcoder members on a taas team will not be added in this interface.

![image](https://user-images.githubusercontent.com/6014049/101051655-bf1f7680-3553-11eb-927a-c4b035b30496.png)

**Comment by maxceem** [comment] 2021-01-19 14:09
Roles mapping between Topcoder and Connect roles:

![image](https://user-images.githubusercontent.com/146016/105045474-9fdf9880-5a70-11eb-8175-f4216f2b2463.png)

**Comment by maxceem** [comment] 2021-01-20 15:47
### Details of this task:
- We would use Projects Service API to manage invitations `​/projects​/{projectId}​/invites` and members `/projects/{projectId}/members`.
- To add a user to the TaaS Team, such user should be invited by `hanlde` or `email`.
- We should list invited users together with members. Invited users should be somehow marked as invited.
- We should be able to remove invitations.
- We would invite all the users as `customer` to the project no matter what Topcoder role it has.
- After user is invited, such user should get email with `Accept` and `Decline` links which should lead to the TaaS App. (Need Project Service and TC Notifications services updates, together with creating template in sendgrid)
- By following these links user would be lead to the TaaS App, and the invitation would be automatically accepted or declined.
- We should be able to remove members.
- Users should be able to leave team.
- User should see the teams they are invited to as listed in the teams page.
- When opening a project they are invited too, the popup with buttons to accept/reject invitation should be shown. Once click `accept` they should be added to the project and project shown. Once clicked `decline` invitation should be declined and they should be redirected to the teams listing page.

### Questions

1. Should users who can see all the teams like bookingmanars be able to join teams directly without an invitation? This is how it's done in Connect. I guess we don't need it, as bookingmanars already can do anything inside teams. But in case we need it for some tracking of assigned managers.

    ![image](https://user-images.githubusercontent.com/146016/105199114-0df68f00-5b47-11eb-8924-c91838f1f51c.png)

**Comment by wdprice** [comment] 2021-01-21 14:45
Lets keep the option to "Join Project" because if we choose to add a feature similar to "My Projects" in Connect then it would make filtering easier for those super users.

**Comment by maxceem** [comment] 2021-02-08 11:55
@wdprice users who is invited to the project should have some UI to accept/decline invitation not only using links from email.

I suggest implementing the same UI like we have in Connect App

### Project List

![image](https://user-images.githubusercontent.com/146016/107215905-a8464600-6a14-11eb-9ca2-e281ad42b7f8.png)

![image](https://user-images.githubusercontent.com/146016/107215965-bb591600-6a14-11eb-9dde-888ce0ac9a19.png)

### Project Details

If user happen to open project by the link where they are invited but not yet join they don' have access to the project (team). So we show prompt to accept or decline an invitation:

![image](https://user-images.githubusercontent.com/146016/107216145-ff4c1b00-6a14-11eb-9a23-eeb6fd4be8ea.png)

### From Email

When user click links in the email, they should be redirected to the Project Details (Tema Details) page with the same dialog, but button should be pressed automatically and loading process should be shown until the accept / reject operation completes.

![image](https://user-images.githubusercontent.com/146016/107216275-37ebf480-6a15-11eb-8028-42ff94e94b02.png)

Could you please, confirm if all of this is desired.

**Comment by wdprice** [comment] 2021-02-11 15:40
@maxceem - I'd like to keep it as simple as possible. Do we need to support the invitation workflow or can we just consider it automatically accepted when added?

**Comment by maxceem** [comment] 2021-02-11 16:17
@wdprice only Topcoder Admins can add members directly or accept invites for other users. So we can only do so, if we restrict this functionality to Topcoder Admins.

Another to achieve this is to create new endpoints in **TaaS API** which would create members directly bypassing the invitation process. **TaaS API** can call **Projects API** using **M2M token** which can also add members directly bypassing the invitation process.
- Creating such endpoints in **TaaS API** could be easier than supporting the whole invitation workflow in the short term. But in long term, we would have to support these endpoints, while otherwise, we would just use **Projects API**.
- Another concern I have, is that such API would give the possibility to bypass the invitation process to any user. I. e. in Projects API by following business requirements we've implemented this invitation workflow when users have to confirm, and here we would create an endpoint that would bypass their confirmation. As a result, any new user which creates an account on Topcoder could create a team, and add there any other Topcoder members without their confirmation. Not sure if it fine or not.
- One more drawback of direct adding. We could invite users by email who is not yet registered on Topcoder. Because at the moment the invitations support invited new users and they would get an email with a registration link.

Let me know if you would like to go this way.

If we stick to reusing the API we have in Projects API, then we cannot bypass the invitation process, though we can simplify a bit one moment. We don't have to implement functionality to accept/decline invites on the project listing page (case 1 in https://github.com/topcoder-platform/taas-app/issues/14#issuecomment-775092446) and only have to implement accept/decline invitation inside the team and from the invitation email (cases 2 and 3 in comment https://github.com/topcoder-platform/taas-app/issues/14#issuecomment-775092446).

**Comment by wdprice** [comment] 2021-02-11 16:30
I'm having a discussion more broadly w/ the Product group on this. Should get an update later today.

**Comment by wdprice** [comment] 2021-02-12 03:09
@maxceem  Go ahead with the M2M workaround. We will need to add some text to explain they can only add topcoder users. We're still discussing if the invitations are the way we want things long term.

**Comment by maxceem** [comment] 2021-02-12 08:18
@wdprice there are a couple more things if we go with direct member adding
- Just realized that even more easier way would be to update Projects API, so it allows adding members directly not only for Topcoder Admins but for other users also (trivial change). Then we even don't have to create new endpoints in TaaS API.
   - but Projects API only supports adding member by "handle" so if we would like to support emails, then we would still have to create TaaS API endpoints or update endpoints in Projects API to support emails
   - anyway, if generally, it's fine for Topcoder to allow adding members directly it would be easier to update Projects API to support it, as there are already endpoints implemented
- There is one small drawback of not supporting the inviting process in TaaS App. At the moment users who are invited but not yet accepted invite can see projects (teams) in the list, but cannot access project (team) details. So if some user is invited but not yet accepted, they would see this team on the list, but once user clicks on it, they would see an error, because they don't have access.

**Comment by maxceem** [comment] 2021-02-23 10:03
Updated requirements.

### Add members instead of invite

When we open this dialog [https://marvelapp.com/prototype/921gg0f/screen/75391358/handoff](https://marvelapp.com/prototype/921gg0f/screen/75391358/handoff) instead of calling endpoint to invite members we have to call API to **add** these users directly as members. 

1. Rename dialog to "Add more people" and rename the button "Invite" to "Add".
2. After success response, we have to **add a member** to the list, not an invite.
3. Remove the logic for adding invites from the source code.
4. Show existent invites on the list, but remove button for deleting invites and related logic. We would not remove invites anymore as we cannot add them but we would still show existent invites.

### QA Guidelines

1. It should allow adding users by **handles** and by **emails** like it's done in Connect, see [screenshot](https://monosnap.com/file/TlAbcNPZVnEiNYdUhnyl9VEyxXvQs8).

2. We also have to allow adding users by handles even if the handle is not listed in suggestions. This is because of 2 reasons: 
    1. Some members might be not returned in suggestions due to data inconsistency.
    2. Some users don't have permission to get suggestions. For example, ``pshah_customer/topcoder123``. This user would not get any suggestions. Please, check that in such case everything works good and we can still add members by handles and emails. Note, that this user can access just a few teams, so use one of these teams [https://platform.topcoder-dev.com/taas/myteams](https://platform.topcoder-dev.com/taas/myteams) (can see after login with `pshah_customer`).

3. If we try to add a member by the **handle** which is already on the list, we have to show validation error immediately like on [screenshot](https://monosnap.com/file/0B4HFMU6XPOGwpXHk9lwaruo9mzy05): "Member(s) cannot be added again. Please, remove them from the field.".
    1. The same if we try to invite member by **email** who is already on the list.
   
4. If there were an error while inviting some of the members, then the server would return the list of successful and the list of failed members: 
    1. don't close popup in such case, 
    2. show the list of errors under the field like in Connect App.
    3. show members which were successfully added on the list (under the popup), and remove handles/email of successfully added members from the field, 
    4. keep failed handles/emails on the field so we can try to add them again, see [video](https://monosnap.com/file/xfCr9OJ7Mlqk5opLS23TXS4ptXqhDg).

**Comment by sandhiyakavi** [comment] 2021-02-23 13:21
@maxceem Below are some issues found.

1. Booking Manager was not able to access the "Manage Access" page .Getting error " You do not have permissions to perform this action" but able to access the project and all its features. Booking Manager is able to access "Manage access" page only when added as member.
credential used: bookingmanager/Appirio123

<img width="960" alt="booking manager_not able to access" src="https://user-images.githubusercontent.com/55895538/108847663-4f38fd80-7623-11eb-9fed-6a2896c77490.png">

2. In success message the count is displayed twice.
<img width="615" alt="success_message_error" src="https://user-images.githubusercontent.com/55895538/108847976-c53d6480-7623-11eb-88e4-a96c73435e5c.png">

3. Suggestions are not displayed for users with only "Topcoder user" role. It's showing "Create" text before every handle/email id. Suggestions are displayed for users like tonyj ,TCConManager etc.
<img width="957" alt="asking for create" src="https://user-images.githubusercontent.com/55895538/108848375-4563ca00-7624-11eb-906c-49db320d942f.png">
<img width="612" alt="suggestion_available_for_admin" src="https://user-images.githubusercontent.com/55895538/108849259-4d703980-7625-11eb-98d9-fad7add06955.png">


4. If the member tries to leave by himself, the message shown in pop up is mentioning like removing some other user. Is it possible to show something similar to Connect?
<img width="959" alt="member leaving by himself" src="https://user-images.githubusercontent.com/55895538/108848824-cf139780-7624-11eb-84a6-86c7e299e50a.png">

![image](https://user-images.githubusercontent.com/55895538/108848793-c4f19900-7624-11eb-8d61-749dcb133709.png)

**Comment by maxceem** [comment] 2021-02-23 14:12
@sandhiyakavi thanks for reviewing.

> 1. Booking Manager was not able to access the "Manage Access" page .Getting error " You do not have permissions to perform this action" but able to access the project and all its features. Booking Manager is able to access "Manage access" page only when added as member.
credential used: bookingmanager/Appirio123

I cannot reproduce this issue, could you please try one more time. And if you still can reproduce it, maybe there any other details which might help me to reproduce it too.

> 2. In success message the count is displayed twice.

Fixed, could you please check it.

> 3. Suggestions are not displayed for users with only "Topcoder user" role. It's showing "Create" text before every handle/email id. Suggestions are displayed for users like tonyj ,TCConManager etc.

This is expected behavior, same in Connect. Regular users don't have permissions to request suggestions.

> 4. If the member tries to leave by himself, the message shown in pop up is mentioning like removing some other user. Is it possible to show something similar to Connect?

Done.

![image](https://user-images.githubusercontent.com/146016/108853287-36165980-75ef-11eb-9bc0-3809929af9f5.png)

**Comment by maxceem** [comment] 2021-02-23 14:25
> 1. Booking Manager was not able to access the "Manage Access" page .Getting error " You do not have permissions to perform this action" but able to access the project and all its features. Booking Manager is able to access "Manage access" page only when added as member.
credential used: bookingmanager/Appirio123

@sandhiyakavi we DO have permission issues for BokingManager users who is not a member of the project and who doesn't have `Connect Manager` role. I've logged a separate issue for this, as this it would take some time to fix https://github.com/topcoder-platform/taas-app/issues/111

**Comment by sandhiyakavi** [comment] 2021-02-24 08:11
@maxceem Another issue I found while testing is for some users (Not for all) ,we are able to add them through handle but not through email id. Getting error message : " User doesn't exist" 

Users: TCConnCopilot/topcoderconnect+Copilot@gmail.com, TopConnCustomer/topcoderconnect+Customer@gmail.com, TCConCopilotMgr/topcoderconnect+CopilotManager@gmail.com, TCConAccountMgr/topcoderconnect+AccountManager@gmail.com, TCConManager/topcoderconnect+Manager@gmail.com

Also the email id is getting removed from the field for these users if failure happens.

<img width="960" alt="add_more_members" src="https://user-images.githubusercontent.com/55895538/108966669-ccb34b00-76c1-11eb-9356-9e09be907c2a.png">
<img width="960" alt="member_adding_through_handle" src="https://user-images.githubusercontent.com/55895538/108966712-db99fd80-76c1-11eb-9dda-794b9d05c9f1.png">

2. The issues mentioned before are working as expected.

<img width="957" alt="toaster_successmsg" src="https://user-images.githubusercontent.com/55895538/108967245-9924f080-76c2-11eb-9026-70027ee036c7.png">
<img width="960" alt="leave_team" src="https://user-images.githubusercontent.com/55895538/108967252-9de9a480-76c2-11eb-8d54-700b6c78619f.png">

**Comment by maxceem** [comment] 2021-02-25 07:43
> @maxceem Another issue I found while testing is for some users (Not for all) ,we are able to add them through handle but not through email id. Getting error message : " User doesn't exist"

> Users: TCConnCopilot/topcoderconnect+Copilot@gmail.com, TopConnCustomer/topcoderconnect+Customer@gmail.com, TCConCopilotMgr/topcoderconnect+CopilotManager@gmail.com, TCConAccountMgr/topcoderconnect+AccountManager@gmail.com, TCConManager/topcoderconnect+Manager@gmail.com

> Also the email id is getting removed from the field for these users if failure happens.

@sandhiyakavi all of this has been fixed and ready for testing on DEV.

**Comment by sandhiyakavi** [comment] 2021-02-25 09:06
Verified on Dev env. Working as expected.


https://user-images.githubusercontent.com/55895538/109129486-0bb1d100-7794-11eb-84d3-efdc6849330c.mp4

**Comment by sandhiyakavi** [comment] 2021-02-26 10:34
Fixed: 🆗 in Production via milestone v1.5

User already added.
![image](https://user-images.githubusercontent.com/55895538/109286972-4c7a1a80-7866-11eb-98d4-e32f9a177c12.png)
![image](https://user-images.githubusercontent.com/55895538/109287006-5a2fa000-7866-11eb-8559-28418db8e013.png)

If invited through connect
![image](https://user-images.githubusercontent.com/55895538/109288971-e642c700-7868-11eb-94ef-13483e840d95.png)

If member removed
![image](https://user-images.githubusercontent.com/55895538/109287911-8e579080-7867-11eb-9228-f95529bf7271.png)
![image](https://user-images.githubusercontent.com/55895538/109289462-96b0cb00-7869-11eb-862f-e1ea6c544332.png)


If multiple members added
![image](https://user-images.githubusercontent.com/55895538/109288237-ee4e3700-7867-11eb-8eb8-b3d2dbd51a02.png)

**Closed** 2021-02-26 10:35 UTC
Labels: QA Pass on Dev, QA Pass on Prod, enhancement
